<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsUraPlugin>true</IsUraPlugin>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>

    <!-- URA 插件元数据 -->
    <PluginInternalName>TeamStadiumOpponentListResponseAnalyzer</PluginInternalName>
    <PluginDisplayName>显示竞技场对手信息</PluginDisplayName>
    <PluginAuthor>离披&amp;Github Contributors</PluginAuthor>
    <PluginDescription>显示团队竞技场对手信息。</PluginDescription>
    <PluginRepositoryUrl>https://github.com/URA-Plugins/TeamStadiumOpponentListResponseAnalyzer</PluginRepositoryUrl>
  </PropertyGroup>

</Project>
